### ISSUE TITLE
feat(shared-thematique) : Flux biodiversité

### ISSUE THREAD

**Issue by MFrangi** [IGNF/geoportail-environnement.beta.gouv.fr#15]
# Besoin

Vérifier qu'on interroge les couches suivantes

- [x]  Coeurs de parcs nationaux
- [x]  Arrêtés de protection de géotope
- [x]  Arrêtés de protection d'habitats naturels
- [x]  Arrêtés de protection de biotope
- [x]  Réserves naturelles de Corse
- [x]  Réserves naturelles nationales
- [x]  Réserves naturelles régionales
- [x]  Périmètres de protection de réserves naturelles
- [x]  Arrêtés de listes de sites d'intérêt géologique
- [x]  Zones d'adhésion de parcs nationaux
- [x]  Réserves biologiques
- [x]  Réserves nationales de chasse et de faune sauvage
- [x]  Sites Natura 2000 au titre de la Directive Habitats
- [x]  Sites Natura 2000 au titre de la Directive Oiseaux
- [x]  Parcs naturels régionaux
- [x]  Conservatoire du littoral - sites sous responsabilité du conservatoire
- [x]  Conservatoires d'espaces naturels

### Flux ZNIEFF Mer

Les flux WFS `PROTECTEDAREAS.ZNIEFF1.SEA:znieff1_mer` et` PROTECTEDAREAS.ZNIEFF2.SEA:znieff2_mer` renvoient des features avec un attribut `url` obsolète. Par exemple, https://inpn.mnhn.fr/zone/znieff/04M000020 au lieu de https://inpn.mnhn.fr/zone/znieffMer/04M000020.

Faut-il utiliser ces flux ?
Si oui, faut-il signaler l'erreur et attendre qu'elle soit corrigée ou bien modifier nous-même la valeur de l'attribut `url` directement dans le code ? 

### Flux Prairies sensibles

L'intersection sur le flux WFS `PRAIRIES.SENSIBLES.BCAE:prairies_sensibles` ne semble pas fonctionner correctement. 
Lorsque je fais une intersection sur un polygone englobant la majeure partie de la France, j'obtiens bien une réponse avec des features ([requête](https://data.geopf.fr/wfs/ows?service=WFS&version=2.0.0&request=GetFeature&outputFormat=application/json&maxFeatures=50&typeName=PRAIRIES.SENSIBLES.BCAE:prairies_sensibles&cql_filter=INTERSECTS(geom,%20MULTIPOLYGON(((-131308.86725969496%206177608.523749294,%20-73994.916464373%205479726.887594491,%20660972.2172638727%205462869.8432429265,%20799199.980946708%206265265.1543774335,%20-131308.86725969496%206177608.523749294,%20-131308.86725969496%206177608.523749294)))))).
Par contre, lors d'une requête avec un petit polygone intersectant un objet "prairie" visible sur la carte (couche "Prairies sensibles" dans le gestionnaire de couche - correspond au flux WMS raster `PRAIRIES.SENSIBLES.BCAE`), j'obtiens une réponse vide ([requête](https://data.geopf.fr/wfs/ows?service=WFS&version=2.0.0&request=GetFeature&outputFormat=application/json&maxFeatures=50&typeName=PRAIRIES.SENSIBLES.BCAE:prairies_sensibles&cql_filter=INTERSECTS(geom,%20MULTIPOLYGON(((30001.76556974012%206221071.30030751,%2032830.63873717908%206218242.427140071,%2038647.75820825074%206219318.195809379,%2031276.750659290075%206222067.382408721,%2030001.76556974012%206221071.30030751,%2030001.76556974012%206221071.30030751)))))).

Faut-il utiliser ce flux ? D'où vient le problème dans les requêtes ?

**Comment by cboucheIGN** [comment]
# Flux ZNIEFF Mer

Effectivement ne pas interogger ces couches, la cible du projet reste les forêts.

# Flux Prairies sensibles

Je sais pas pourquoi il n'y a pas de résultats, vérifié qu'elle fait partie des couches retenues sinon la viré des candidats

**Comment by MFrangi** [comment]
Je n'ai pas trouvé à quelle couche correspond "Zones d'adhésion de parcs nationaux".

**Comment by cboucheIGN** [comment]
16 / 17 couches dispo sur main

**Comment by cboucheIGN** [comment]
Zones d'adhésion de parcs nationaux dans la même couche que  Coeurs de parcs nationaux. Ce sont juste des objets différents (voir attributs)
