### ISSUE TITLE
Bug(thematic): Information dans les onglets

### ISSUE THREAD

**Issue by David-IGN** [IGNF/geoportail-environnement.beta.gouv.fr#36]
Action pour reproduire le bug : 

1. Allez sur https://gpe.mut-dev.ign.fr/
2. Cliquer sur l'onglet "Mes Forêts"
3. Cliquer sur "Voir le détail"
Visualisation de l'onglet "Patrimoine" : 
![image](https://github.com/user-attachments/assets/e28cd830-bf8a-4064-bbf5-1c591288279e)
4. Cliquer sur l'onglet "Synthèse"
5. Décocher Biodiversité
6. Cliquer sur l'onglet "Patrimoine"
![image](https://github.com/user-attachments/assets/7aa8aba0-e1b1-48ac-b49d-9853fb466185)

-> Les informations lié au patrimoine ne sont pas charger dans l'onglet

Par contre aucun soucis si l'on décoche "Patrimoine". Les informations de "Biodiversité" sont bien charger.

Autre constat.

Si l'on décoche "Biodiversité" et "Patrimoine" et que l'on re-coche "Patrimoine" les informations de "Patrimoine" sont bien affiché.

**Comment by cboucheIGN** [comment]
Ok cette fonctionnalité n'a pas encore été traité. C'est pris en charge dans l'évolution fonctionnelle
* [ ] Lié un réglement pour chaque couche intérogé

**Comment by cboucheIGN** [comment]
Vue avec l'équipe projet. La fonctionnalité est obsolète.
